# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizations',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('isTeacher', models.BooleanField()),
                ('research', models.BooleanField()),
                ('paper', models.BooleanField()),
                ('competition', models.BooleanField()),
                ('exchange', models.BooleanField()),
                ('ideologyConstruction', models.BooleanField()),
                ('lecture', models.BooleanField()),
                ('volunteering', models.BooleanField()),
                ('schoolActivity', models.BooleanField()),
                ('internship', models.BooleanField()),
                ('studentCadre', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('ProjectTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('rankName', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=20)),
                ('rank', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('startingTime', models.DateField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('ProjectName', models.CharField(max_length=20)),
                ('targetName', models.CharField(max_length=20)),
                ('ProjectContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('nature', models.CharField(max_length=20)),
                ('score', models.SmallIntegerField()),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdeologyConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IdeologyConstructionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('rankName', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('score', models.SmallIntegerField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspectorNum', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\xae\xa1\xe6\x9f\xa5\xe8\x80\x85')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('rankName', models.CharField(max_length=20)),
                ('Time', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('contribution', models.TextField()),
                ('report', models.TextField()),
                ('appraisal', models.TextField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('InternshipTime', models.DateField()),
                ('score', models.SmallIntegerField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LectureRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('rankName', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
                ('speaker', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('score', models.SmallIntegerField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('ProjectName', models.CharField(max_length=20)),
                ('ProjectTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('rankName', models.CharField(max_length=50)),
                ('journalName', models.CharField(max_length=20)),
                ('Level', models.CharField(max_length=20)),
                ('AuthorRanking', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('startingTime', models.DateField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('ProjectTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProjectRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('rank', models.CharField(max_length=20)),
                ('ManagerScore', models.SmallIntegerField()),
                ('MemberScore', models.SmallIntegerField(null=True)),
                ('startingTime', models.DateField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolActivityRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(max_length=50)),
                ('rankName', models.CharField(max_length=20)),
                ('sponsor', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('awardLevel', models.CharField(max_length=50)),
                ('score', models.SmallIntegerField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('opinions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCadreRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('organizitionType', models.CharField(max_length=50)),
                ('organizitionName', models.CharField(max_length=20)),
                ('rankName', models.CharField(max_length=20)),
                ('score', models.SmallIntegerField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentNum', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rankName', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('year', models.PositiveSmallIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('born', models.DateField()),
                ('root', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('politicalStatus', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('identityType', models.CharField(max_length=20)),
                ('identityNumber', models.BigIntegerField()),
                ('speciality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('collegeEntranceExaminationScore', models.PositiveSmallIntegerField()),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Authorizations')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('StudentNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteeringRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('rankName', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('volunteerTime', models.PositiveIntegerField()),
                ('Content', models.TextField()),
                ('score', models.SmallIntegerField()),
                ('CompleteNum', models.PositiveIntegerField()),
                ('SupportText', models.TextField(null=True)),
                ('inspectorNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
                ('teacherNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
            ],
        ),
        migrations.AddField(
            model_name='volunteering',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VolunteeringRank'),
        ),
        migrations.AddField(
            model_name='studentcadrerank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='studentcadre',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='studentcadre',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='studentcadre',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StudentCadreRank'),
        ),
        migrations.AddField(
            model_name='schoolactivityrank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SchoolActivityRank'),
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ResearchProjectRank'),
        ),
        migrations.AddField(
            model_name='paperrank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='paper',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='paper',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='paper',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PaperRank'),
        ),
        migrations.AddField(
            model_name='lecturerank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LectureRank'),
        ),
        migrations.AddField(
            model_name='internshiprank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='internship',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='internship',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='internship',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InternshipRank'),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IdeologyConstructionRank'),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExchangeRank'),
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='teacherNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='competition',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='competition',
            name='inspectorNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='competition',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompetitionRank'),
        ),
    ]
