# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizations',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('isTeacher', models.BooleanField()),
                ('research', models.BooleanField()),
                ('paper', models.BooleanField()),
                ('competition', models.BooleanField()),
                ('exchange', models.BooleanField()),
                ('ideologyConstruction', models.BooleanField()),
                ('lecture', models.BooleanField()),
                ('volunteering', models.BooleanField()),
                ('schoolActivity', models.BooleanField()),
                ('internship', models.BooleanField()),
                ('studentCadre', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('complete', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('managerScore', models.SmallIntegerField()),
                ('memberScore', models.SmallIntegerField()),
                ('managerComplete', models.SmallIntegerField()),
                ('memberComplete', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('rankName', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('startingTime', models.DateField()),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete1', models.SmallIntegerField()),
                ('complete2', models.SmallIntegerField()),
                ('complete3', models.SmallIntegerField()),
                ('complete4', models.SmallIntegerField()),
                ('complete5', models.SmallIntegerField()),
                ('complete6', models.SmallIntegerField()),
                ('complete7', models.SmallIntegerField()),
                ('complete8', models.SmallIntegerField()),
                ('complete9', models.SmallIntegerField()),
                ('complete10', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompleteInformation',
            fields=[
                ('Complete', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('CompleteExplain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('nature', models.CharField(max_length=20)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdeologyConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IdeologyConstructionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('rankName', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\xae\xa1\xe6\x9f\xa5\xe8\x80\x85')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('rankName', models.CharField(max_length=20)),
                ('Time', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('contribution', models.TextField()),
                ('report', models.TextField()),
                ('appraisal', models.TextField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InternshipRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('InternshipTime', models.DateField()),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LectureRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('rankName', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
                ('speaker', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='PaperRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('rankName', models.CharField(max_length=50)),
                ('journalName', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('AuthorRanking', models.SmallIntegerField()),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('startingTime', models.DateField()),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProjectRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('rank', models.CharField(max_length=20)),
                ('ManagerScore', models.SmallIntegerField(blank=True, null=True)),
                ('MemberScore', models.SmallIntegerField(blank=True, null=True)),
                ('startingTime', models.DateField()),
                ('ManagerComplete', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('MemberComplete', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolActivityRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('rankName', models.CharField(max_length=20)),
                ('sponsor', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('awardLevel', models.CharField(max_length=50)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCadreRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('organizitionType', models.CharField(max_length=50)),
                ('organizitionName', models.CharField(max_length=20)),
                ('rankName', models.CharField(max_length=20)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentNum', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rankName', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('year', models.PositiveSmallIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('born', models.DateField()),
                ('root', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('politicalStatus', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('identityType', models.CharField(max_length=20)),
                ('identityNumber', models.BigIntegerField()),
                ('speciality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('collegeEntranceExaminationScore', models.PositiveSmallIntegerField()),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Authorizations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('StudentNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteeringRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10)),
                ('rankName', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
                ('startingTime', models.DateField()),
                ('Location', models.CharField(max_length=50)),
                ('volunteerTime', models.PositiveIntegerField()),
                ('Content', models.TextField()),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('complete', models.PositiveIntegerField(blank=True, null=True)),
                ('SupportText', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
            ],
        ),
        migrations.AddField(
            model_name='volunteering',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VolunteeringRank'),
        ),
        migrations.AddField(
            model_name='studentcadrerank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivityrank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SchoolActivityRank'),
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ResearchProjectRank'),
        ),
        migrations.AddField(
            model_name='paperrank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecturerank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LectureRank'),
        ),
        migrations.AddField(
            model_name='internshiprank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='internship',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='internship',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='internship',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InternshipRank'),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IdeologyConstructionRank'),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
    ]
