# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizations',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=b'id')),
                ('isTeacher', models.BooleanField(verbose_name=b'\xe6\x95\x99\xe5\xb8\x88\xe6\x9d\x83\xe9\x99\x90')),
                ('research', models.BooleanField(verbose_name=b'\xe7\xa7\x91\xe7\xa0\x94\xe7\xab\x8b\xe9\xa1\xb9\xe6\x9d\x83\xe9\x99\x90')),
                ('paper', models.BooleanField(verbose_name=b'\xe5\xad\xa6\xe6\x9c\xaf\xe8\xae\xba\xe6\x96\x87\xe6\x9d\x83\xe9\x99\x90')),
                ('competition', models.BooleanField(verbose_name=b'\xe5\xad\xa6\xe6\x9c\xaf\xe7\xab\x9e\xe8\xb5\x9b\xe6\x9d\x83\xe9\x99\x90')),
                ('exchange', models.BooleanField(verbose_name=b'\xe4\xba\xa4\xe6\xb5\x81\xe4\xba\xa4\xe6\x8d\xa2\xe6\x9d\x83\xe9\x99\x90')),
                ('ideologyConstruction', models.BooleanField(verbose_name=b'\xe6\x80\x9d\xe5\xbb\xba\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x9d\x83\xe9\x99\x90')),
                ('lecture', models.BooleanField(verbose_name=b'\xe8\xae\xb2\xe5\xba\xa7\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x9d\x83\xe9\x99\x90')),
                ('volunteering', models.BooleanField(verbose_name=b'\xe5\xbf\x97\xe6\x84\xbf\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x9d\x83\xe9\x99\x90')),
                ('schoolActivity', models.BooleanField(verbose_name=b'\xe6\xa0\xa1\xe5\x9b\xad\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x9d\x83\xe9\x99\x90')),
                ('internship', models.BooleanField(verbose_name=b'\xe5\xae\x9e\xe8\xb7\xb5\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x9d\x83\xe9\x99\x90')),
                ('studentCadre', models.BooleanField(verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xb9\xb2\xe9\x83\xa8\xe6\x9d\x83\xe9\x99\x90')),
            ],
            options={
                'verbose_name': '\u6743\u9650',
                'verbose_name_plural': '\u6743\u9650',
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe9\x98\x9f\xe4\xbc\x8d\xe5\x90\x8d\xe7\xa7\xb0')),
                ('score', models.SmallIntegerField(blank=True, null=True, verbose_name=b'\xe5\x88\x86\xe6\x95\xb0')),
            ],
            options={
                'verbose_name': '\u8bc4\u4ef7\u7b49\u7ea7',
                'verbose_name_plural': '\u8bc4\u4ef7\u7b49\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='ChoicesTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe9\x98\x9f\xe4\xbc\x8d\xe5\x90\x8d\xe7\xa7\xb0')),
                ('managerScore', models.SmallIntegerField(verbose_name=b'\xe9\x98\x9f\xe9\x95\xbf\xe5\x88\x86\xe6\x95\xb0')),
                ('memberScore', models.SmallIntegerField(verbose_name=b'\xe9\x98\x9f\xe5\x91\x98\xe5\x88\x86\xe6\x95\xb0')),
            ],
            options={
                'verbose_name': '\u79d1\u7814\u7acb\u9879\u8bc4\u4ef7\u7b49\u7ea7',
                'verbose_name_plural': '\u79d1\u7814\u7acb\u9879\u8bc4\u4ef7\u7b49\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='CompetitionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('rankName', models.CharField(max_length=50, verbose_name=b'\xe5\xad\xa6\xe6\x9c\xaf\xe7\xab\x9e\xe8\xb5\x9b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('Level', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe6\x9c\xaf\xe7\xab\x9e\xe8\xb5\x9b\xe7\xad\x89\xe7\xba\xa7')),
                ('rank', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe6\x8e\x92\xe5\x90\x8d')),
                ('startingTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
            ],
            options={
                'verbose_name': '\u5b66\u672f\u7ade\u8d5b',
                'verbose_name_plural': '\u5b66\u672f\u7ade\u8d5b',
            },
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete1', models.SmallIntegerField()),
                ('complete2', models.SmallIntegerField()),
                ('complete3', models.SmallIntegerField()),
                ('complete4', models.SmallIntegerField()),
                ('complete5', models.SmallIntegerField()),
                ('complete6', models.SmallIntegerField()),
                ('complete7', models.SmallIntegerField()),
                ('complete8', models.SmallIntegerField()),
                ('complete9', models.SmallIntegerField()),
                ('complete0', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '\u5b8c\u6210\u5ea6',
                'verbose_name_plural': '\u5b8c\u6210\u5ea6',
            },
        ),
        migrations.CreateModel(
            name='CompleteInformation',
            fields=[
                ('Complete', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name=b'\xe5\xae\x8c\xe6\x88\x90\xe5\xba\xa6')),
                ('CompleteExplain', models.TextField(verbose_name=b'\xe5\xae\x8c\xe6\x88\x90\xe5\xba\xa6\xe7\xae\x80\xe4\xbb\x8b')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=50, verbose_name=b'\xe5\xaf\xb9\xe6\x96\xb9\xe9\x99\xa2\xe6\xa0\xa1/\xe6\x9c\xba\xe6\x9e\x84\xe5\x90\x8d\xe7\xa7\xb0')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('type', models.CharField(max_length=50, verbose_name=b'\xe4\xba\xa4\xe6\x8d\xa2\xe7\xb1\xbb\xe5\x88\xab')),
                ('nature', models.CharField(max_length=20, verbose_name=b'\xe4\xba\xa4\xe6\xb5\x81\xe6\x80\xa7\xe8\xb4\xa8')),
                ('startTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('endTime', models.DateField(verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
            ],
            options={
                'verbose_name': '\u4ea4\u6d41\u4ea4\u6362',
                'verbose_name_plural': '\u4ea4\u6d41\u4ea4\u6362',
            },
        ),
        migrations.CreateModel(
            name='IdeologyConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'verbose_name': '\u601d\u5efa\u6d3b\u52a8\u5176\u4ed6\u4fe1\u606f',
                'verbose_name_plural': '\u601d\u5efa\u6d3b\u52a8\u5176\u4ed6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='IdeologyConstructionRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('type', models.CharField(max_length=50, verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe7\xb1\xbb\xe5\x88\xab')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('organizer', models.CharField(max_length=50, verbose_name=b'\xe4\xb8\xbb\xe5\x8a\x9e\xe6\x96\xb9')),
                ('startingTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('Location', models.CharField(max_length=50, verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x9c\xb0\xe7\x82\xb9')),
                ('Content', models.TextField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x86\x85\xe5\xae\xb9')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
            ],
            options={
                'verbose_name': '\u601d\u5efa\u6d3b\u52a8',
                'verbose_name_plural': '\u601d\u5efa\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='Inspectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name=b'\xe5\xae\xa1\xe6\x9f\xa5\xe8\x80\x85\xe7\xbc\x96\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe5\xae\xa1\xe6\xa0\xb8\xe8\x80\x85\xe5\x90\x8d\xe7\xa7\xb0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\xae\xa1\xe6\x9f\xa5\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u5ba1\u6838\u8005',
                'verbose_name_plural': '\u5ba1\u6838\u8005',
            },
        ),
        migrations.CreateModel(
            name='InternshipRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe5\xae\x9e\xe4\xb9\xa0\xe5\x90\x8d\xe7\xa7\xb0')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('type', models.CharField(max_length=50, verbose_name=b'\xe5\xae\x9e\xe4\xb9\xa0\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('Time', models.DateField(verbose_name=b'\xe5\xae\x9e\xe4\xb9\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('location', models.CharField(max_length=50, verbose_name=b'\xe5\xae\x9e\xe4\xb9\xa0\xe5\x9c\xb0\xe7\x82\xb9')),
                ('job', models.CharField(max_length=50, verbose_name=b'\xe5\xae\x9e\xe4\xb9\xa0\xe5\xb2\x97\xe4\xbd\x8d')),
                ('contribution', models.TextField(verbose_name=b'\xe8\xb4\xa1\xe7\x8c\xae')),
                ('report', models.TextField(verbose_name=b'\xe5\xae\x9e\xe4\xb9\xa0\xe5\xae\x9e\xe8\xb7\xb5\xe6\x8a\xa5\xe5\x91\x8a')),
                ('appraisal', models.TextField(verbose_name=b'\xe5\xae\x9e\xe4\xb9\xa0\xe9\x89\xb4\xe5\xae\x9a')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
            options={
                'verbose_name': '\u5b9e\u4e60\u5b9e\u8df5',
                'verbose_name_plural': '\u5b9e\u4e60\u5b9e\u8df5',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'verbose_name': '\u5b66\u672f\u8bb2\u5ea7\u5176\u4ed6\u4fe1\u606f',
                'verbose_name_plural': '\u5b66\u672f\u8bb2\u5ea7\u5176\u4ed6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='LectureRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('type', models.CharField(max_length=50, verbose_name=b'\xe8\xae\xb2\xe5\xba\xa7\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe8\xae\xb2\xe5\xba\xa7\xe5\x90\x8d\xe7\xa7\xb0')),
                ('organizer', models.CharField(max_length=50, verbose_name=b'\xe4\xb8\xbb\xe5\x8a\x9e\xe6\x96\xb9')),
                ('speaker', models.CharField(max_length=50, verbose_name=b'\xe4\xb8\xbb\xe8\xae\xb2\xe4\xba\xba')),
                ('startingTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('Location', models.CharField(max_length=50, verbose_name=b'\xe8\xae\xb2\xe5\xba\xa7\xe5\x9c\xb0\xe7\x82\xb9')),
                ('Content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9\xe7\xae\x80\xe4\xbb\x8b')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
            options={
                'verbose_name': '\u5b66\u672f\u8bb2\u5ea7',
                'verbose_name_plural': '\u5b66\u672f\u8bb2\u5ea7',
            },
        ),
        migrations.CreateModel(
            name='PaperRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('rankName', models.CharField(max_length=50, verbose_name=b'\xe8\xae\xba\xe6\x96\x87\xe5\x90\x8d\xe7\xa7\xb0')),
                ('journalName', models.CharField(max_length=20, verbose_name=b'\xe6\x9c\x9f\xe5\x88\x8a\xe5\x90\x8d\xe7\xa7\xb0')),
                ('rank', models.CharField(max_length=20, verbose_name=b'\xe7\xad\x89\xe7\xba\xa7')),
                ('AuthorRanking', models.SmallIntegerField(verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85\xe9\xa1\xba\xe5\xba\x8f')),
                ('startingTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
            options={
                'verbose_name': '\u8bba\u6587',
                'verbose_name_plural': '\u8bba\u6587',
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'verbose_name': '\u79d1\u7814\u7acb\u9879\u5176\u4ed6\u4fe1\u606f',
                'verbose_name_plural': '\u79d1\u7814\u7acb\u9879\u5176\u4ed6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe7\xa7\x91\xe7\xa0\x94\xe7\xab\x8b\xe9\xa1\xb9\xe5\x90\x8d\xe7\xa7\xb0')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('rank', models.CharField(max_length=20, verbose_name=b'\xe7\xa7\x91\xe7\xa0\x94\xe7\xab\x8b\xe9\xa1\xb9\xe7\xad\x89\xe7\xba\xa7')),
                ('startingTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ChoicesTeam', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors', verbose_name=b'\xe5\xae\xa1\xe6\xa0\xb8\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u79d1\u7814\u7acb\u9879',
                'verbose_name_plural': '\u79d1\u7814\u7acb\u9879',
            },
        ),
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'verbose_name': '\u6821\u56ed\u6d3b\u52a8\u5176\u4ed6\u4fe1\u606f',
                'verbose_name_plural': '\u6821\u56ed\u6d3b\u52a8\u5176\u4ed6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='SchoolActivityRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('type', models.CharField(max_length=50, verbose_name=b'\xe6\xa0\xa1\xe5\x9b\xad\xe6\xb4\xbb\xe5\x8a\xa8\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('sponsor', models.CharField(max_length=50, verbose_name=b'\xe6\x89\xbf\xe5\x8a\x9e\xe6\x96\xb9')),
                ('organizer', models.CharField(max_length=50, verbose_name=b'\xe4\xb8\xbb\xe5\x8a\x9e\xe6\x96\xb9')),
                ('startingTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('awardLevel', models.CharField(max_length=50, verbose_name=b'\xe5\xa5\x96\xe9\xa1\xb9')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
            options={
                'verbose_name': '\u6821\u56ed\u6d3b\u52a8',
                'verbose_name_plural': '\u6821\u56ed\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='StudentCadreRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('organizitionType', models.CharField(max_length=50, verbose_name=b'\xe7\xbb\x84\xe7\xbb\x87\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('organizitionName', models.CharField(max_length=20, verbose_name=b'\xe7\xbb\x84\xe7\xbb\x87\xe5\x90\x8d\xe7\xa7\xb0')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xb9\xb2\xe9\x83\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
            options={
                'verbose_name': '\u5b66\u751f\u5e72\u90e8',
                'verbose_name_plural': '\u5b66\u751f\u5e72\u90e8',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentNum', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xa7\x93\xe5\x90\x8d')),
                ('sex', models.BooleanField(verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('year', models.PositiveSmallIntegerField(verbose_name=b'\xe5\x85\xa5\xe5\xad\xa6\xe5\xb9\xb4\xe4\xbb\xbd')),
                ('phone', models.BigIntegerField(verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81')),
                ('email', models.EmailField(max_length=254, verbose_name=b'\xe7\x94\xb5\xe5\xad\x90\xe9\x82\xae\xe7\xae\xb1')),
                ('born', models.DateField(verbose_name=b'\xe5\x87\xba\xe7\x94\x9f\xe5\xb9\xb4\xe6\x9c\x88')),
                ('root', models.CharField(max_length=50, verbose_name=b'\xe7\xb1\x8d\xe8\xb4\xaf')),
                ('nation', models.CharField(max_length=50, verbose_name=b'\xe6\xb0\x91\xe6\x97\x8f')),
                ('politicalStatus', models.CharField(max_length=50, verbose_name=b'\xe6\x94\xbf\xe6\xb2\xbb\xe9\x9d\xa2\xe8\xb2\x8c')),
                ('location', models.CharField(max_length=50, verbose_name=b'\xe5\x9b\xbd\xe5\xae\xb6\xe5\x9c\xb0\xe5\x8c\xba')),
                ('identityType', models.CharField(max_length=20, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe4\xbb\xb6\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('identityNumber', models.BigIntegerField(verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7\xe7\xa0\x81')),
                ('speciality', models.CharField(max_length=50, verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe5\x90\x8d\xe7\xa7\xb0')),
                ('province', models.CharField(max_length=50, verbose_name=b'\xe7\x94\x9f\xe6\xba\x90\xe7\x9c\x81\xe4\xbb\xbd')),
                ('collegeEntranceExaminationScore', models.PositiveSmallIntegerField(verbose_name=b'\xe9\xab\x98\xe8\x80\x83\xe5\x88\x86\xe6\x95\xb0')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Authorizations', verbose_name=b'\xe6\x9d\x83\xe9\x99\x90')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f',
            },
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('StudentNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
            ],
            options={
                'verbose_name': '\u5fd7\u613f\u6d3b\u52a8\u5176\u4ed6\u4fe1\u606f',
                'verbose_name_plural': '\u5fd7\u613f\u6d3b\u52a8\u5176\u4ed6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='VolunteeringRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('rankName', models.CharField(max_length=20, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('organizer', models.CharField(max_length=50, verbose_name=b'\xe7\xbb\x84\xe7\xbb\x87\xe8\x80\x85')),
                ('startingTime', models.DateField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('Location', models.CharField(max_length=50, verbose_name=b'\xe5\xbf\x97\xe6\x84\xbf\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x9c\xb0\xe7\x82\xb9')),
                ('volunteerTime', models.PositiveIntegerField(verbose_name=b'\xe5\xbf\x97\xe6\x84\xbf\xe6\x97\xb6\xe9\x97\xb4')),
                ('Content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9\xe7\xae\x80\xe4\xbb\x8b')),
                ('SupportText', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe6\x92\x91\xe6\x96\x87\xe6\xa1\xa3')),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students')),
            ],
            options={
                'verbose_name': '\u5fd7\u613f\u6d3b\u52a8',
                'verbose_name_plural': '\u5fd7\u613f\u6d3b\u52a8',
            },
        ),
        migrations.AddField(
            model_name='volunteering',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VolunteeringRank'),
        ),
        migrations.AddField(
            model_name='studentcadrerank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivityrank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SchoolActivityRank'),
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students', verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc\xe6\x95\x99\xe5\xb8\x88'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students', verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ResearchProjectRank'),
        ),
        migrations.AddField(
            model_name='paperrank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecturerank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LectureRank'),
        ),
        migrations.AddField(
            model_name='internshiprank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='StudentNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students', verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IdeologyConstructionRank', verbose_name=b'\xe6\x80\x9d\xe5\xbb\xba\xe6\xb4\xbb\xe5\x8a\xa8\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inspectors'),
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='choicesteam',
            name='managerComplete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Complete', verbose_name=b'\xe9\x98\x9f\xe9\x95\xbf\xe5\xae\x8c\xe6\x88\x90\xe5\xba\xa6'),
        ),
        migrations.AddField(
            model_name='choicesteam',
            name='memberComplete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberComplete', to='app.Complete', verbose_name=b'\xe9\x98\x9f\xe5\x91\x98\xe5\xae\x8c\xe6\x88\x90\xe5\xba\xa6'),
        ),
        migrations.AddField(
            model_name='choices',
            name='complete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Complete', verbose_name=b'\xe5\xae\x8c\xe6\x88\x90\xe5\xba\xa6'),
        ),
    ]
