# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name=b'\xe5\x87\xba\xe7\x94\x9f\xe5\xb9\xb4\xe6\x9c\x88'),
        ),
        migrations.AlterField(
            model_name='students',
            name='collegeEntranceExaminationScore',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'\xe9\xab\x98\xe8\x80\x83\xe5\x88\x86\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'\xe7\x94\xb5\xe5\xad\x90\xe9\x82\xae\xe7\xae\xb1'),
        ),
        migrations.AlterField(
            model_name='students',
            name='identityType',
            field=models.CharField(default=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81', max_length=20, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe4\xbb\xb6\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='students',
            name='location',
            field=models.CharField(default=b'\xe6\x9c\xaa\xe7\x9f\xa5', max_length=50, verbose_name=b'\xe5\x9b\xbd\xe5\xae\xb6\xe5\x9c\xb0\xe5\x8c\xba'),
        ),
        migrations.AlterField(
            model_name='students',
            name='nation',
            field=models.CharField(default=b'\xe6\x9c\xaa\xe7\x9f\xa5', max_length=50, verbose_name=b'\xe6\xb0\x91\xe6\x97\x8f'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='students',
            name='politicalStatus',
            field=models.CharField(default=b'\xe6\x9c\xaa\xe7\x9f\xa5', max_length=50, verbose_name=b'\xe6\x94\xbf\xe6\xb2\xbb\xe9\x9d\xa2\xe8\xb2\x8c'),
        ),
        migrations.AlterField(
            model_name='students',
            name='province',
            field=models.CharField(default=b'\xe6\x9c\xaa\xe7\x9f\xa5', max_length=50, verbose_name=b'\xe7\x94\x9f\xe6\xba\x90\xe7\x9c\x81\xe4\xbb\xbd'),
        ),
        migrations.AlterField(
            model_name='students',
            name='root',
            field=models.CharField(default=b'\xe6\x9c\xaa\xe7\x9f\xa5', max_length=50, verbose_name=b'\xe7\xb1\x8d\xe8\xb4\xaf'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sex',
            field=models.BooleanField(default=True, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab'),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'\xe5\x85\xa5\xe5\xad\xa6\xe5\xb9\xb4\xe4\xbb\xbd'),
        ),
    ]
