# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherNum', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='inspectors',
            old_name='inspectorID',
            new_name='inspectorNum',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='StudentID',
            new_name='StudentNum',
        ),
        migrations.AddField(
            model_name='relation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
        ),
        migrations.AddField(
            model_name='projects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teachers'),
        ),
    ]
