# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': '\u8f85\u5bfc\u5458', 'verbose_name_plural': '\u8f85\u5bfc\u5458'},
        ),
        migrations.AddField(
            model_name='instructor',
            name='num',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe6\x95\x99\xe5\xb7\xa5\xe5\x8f\xb7'),
            preserve_default=False,
        ),
    ]
