# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionrank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='exchangerank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='ideologyconstructionrank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='internshiprank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='lecturerank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='paperrank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='researchprojectrank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ChoicesTeam', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='schoolactivityrank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='studentcadrerank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='volunteeringrank',
            name='Choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7'),
        ),
    ]
