# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-01 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170430_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=50, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('rnum', models.PositiveSmallIntegerField(verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe4\xb8\xbb\xe9\x94\xae')),
                ('role', models.BooleanField(default=0, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd')),
                ('status', models.CharField(choices=[(b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choices', verbose_name=b'\xe8\xaf\x84\xe4\xbb\xb7\xe7\xad\x89\xe7\xba\xa7')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LtoS', to='app.Students', verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8-\u5b66\u751f\u5173\u7cfb\u8868',
                'verbose_name_plural': '\u6d3b\u52a8-\u5b66\u751f\u5173\u7cfb\u8868',
            },
        ),
        migrations.RemoveField(
            model_name='ideologyconstruction',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='ideologyconstruction',
            name='StudentNum',
        ),
        migrations.RemoveField(
            model_name='ideologyconstruction',
            name='rankNum',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='StudentNum',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='rankNum',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='StudentNum',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='rankNum',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='StudentNum',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='rankNum',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='StudentNum',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='rankNum',
        ),
        migrations.RemoveField(
            model_name='competitionrank',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='competitionrank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='competitionrank',
            name='status',
        ),
        migrations.RemoveField(
            model_name='competitionrank',
            name='student',
        ),
        migrations.RemoveField(
            model_name='exchangerank',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='exchangerank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='exchangerank',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exchangerank',
            name='student',
        ),
        migrations.RemoveField(
            model_name='ideologyconstructionrank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='ideologyconstructionrank',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='internshiprank',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='internshiprank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='internshiprank',
            name='status',
        ),
        migrations.RemoveField(
            model_name='internshiprank',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lecturerank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='paperrank',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='paperrank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='paperrank',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paperrank',
            name='student',
        ),
        migrations.RemoveField(
            model_name='researchprojectrank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='schoolactivityrank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='studentcadrerank',
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='studentcadrerank',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='studentcadrerank',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentcadrerank',
            name='student',
        ),
        migrations.RemoveField(
            model_name='volunteeringrank',
            name='SupportText',
        ),
        migrations.DeleteModel(
            name='IdeologyConstruction',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='ResearchProject',
        ),
        migrations.DeleteModel(
            name='SchoolActivity',
        ),
        migrations.DeleteModel(
            name='Volunteering',
        ),
    ]
