# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161220_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.SmallIntegerField()),
                ('complete', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('managerScore', models.SmallIntegerField()),
                ('memberScore', models.SmallIntegerField()),
                ('managerComplete', models.SmallIntegerField()),
                ('memberComplete', models.SmallIntegerField()),
            ],
        ),
    ]
