# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-29 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171119_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='complete',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AddField(
            model_name='major',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'\xe5\x85\xa5\xe5\xad\xa6\xe5\xb9\xb4\xe4\xbb\xbd'),
        ),
    ]
