# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161024_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
