# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_choices_choicesteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchprojectrank',
            name='CompleteNum',
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='ManagerComplete',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='MemberComplete',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
