# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161209_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizations',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('isTeacher', models.BooleanField()),
                ('research', models.BooleanField()),
                ('paper', models.BooleanField()),
                ('competition', models.BooleanField()),
                ('exchange', models.BooleanField()),
                ('ideologyConstruction', models.BooleanField()),
                ('lecture', models.BooleanField()),
                ('volunteering', models.BooleanField()),
                ('schoolActivity', models.BooleanField()),
                ('internship', models.BooleanField()),
                ('studentCadre', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='classbasis',
            name='inspectorNum',
        ),
        migrations.RemoveField(
            model_name='classscore',
            name='StudentNum',
        ),
        migrations.RemoveField(
            model_name='classscore',
            name='inspectorNum',
        ),
        migrations.RemoveField(
            model_name='completeinformation',
            name='inspectorNum',
        ),
        migrations.DeleteModel(
            name='Completeness',
        ),
        migrations.RemoveField(
            model_name='inclass',
            name='inspectorNum',
        ),
        migrations.RemoveField(
            model_name='majorname',
            name='inspectorNum',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentMajor',
        ),
        migrations.RemoveField(
            model_name='teacherbasis',
            name='inspectorNum',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='user',
        ),
        migrations.DeleteModel(
            name='TrainingProject',
        ),
        migrations.AddField(
            model_name='lecturerank',
            name='teacherNum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='rankName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='StudentNum',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7'),
        ),
        migrations.DeleteModel(
            name='ClassBasis',
        ),
        migrations.DeleteModel(
            name='ClassScore',
        ),
        migrations.DeleteModel(
            name='CompleteInformation',
        ),
        migrations.DeleteModel(
            name='InClass',
        ),
        migrations.DeleteModel(
            name='Majorname',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='TeacherBasis',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='students',
            name='auth',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Authorizations'),
            preserve_default=False,
        ),
    ]
