# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161219_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='identityNumber',
            field=models.BigIntegerField(),
        ),
    ]
