# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projects_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('pigid', models.IntegerField(db_column=b'ID', primary_key=True, serialize=False)),
                ('pigname', models.CharField(max_length=20)),
            ],
        ),
    ]
