# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-29 14:12
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/media'), upload_to=b'')),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '\u6d88\u606f', 'verbose_name_plural': '\u6d88\u606f'},
        ),
    ]
