# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161213_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exchange',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ideologyconstruction',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='internshiprank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lecturerank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paperrank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolactivity',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolactivityrank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentcadre',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentcadrerank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='volunteering',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='volunteeringrank',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='competition',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompetitionRank'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ExchangeRank'),
        ),
        migrations.AlterField(
            model_name='ideologyconstruction',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IdeologyConstructionRank'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.InternshipRank'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LectureRank'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PaperRank'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ResearchProjectRank'),
        ),
        migrations.AlterField(
            model_name='schoolactivity',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SchoolActivityRank'),
        ),
        migrations.AlterField(
            model_name='studentcadre',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StudentCadreRank'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='rankNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VolunteeringRank'),
        ),
    ]
