# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-29 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171129_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
