# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170109_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionrank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='exchangerank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='ideologyconstructionrank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='internshiprank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='lecturerank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='paperrank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='schoolactivityrank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='studentcadrerank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
        migrations.RenameField(
            model_name='volunteeringrank',
            old_name='CompleteNum',
            new_name='Complete',
        ),
    ]
