# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-01 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170501_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionrank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='exchangerank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='ideologyconstructionrank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='internshiprank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='lecturerank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='paperrank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='researchprojectrank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='schoolactivityrank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='studentcadrerank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
        migrations.AlterField(
            model_name='volunteeringrank',
            name='active',
            field=models.BooleanField(default=1, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe6\x80\xa7'),
        ),
    ]
