# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161219_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='ideologyconstruction',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='schoolactivity',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='studentcadre',
            name='SupportText',
        ),
        migrations.RemoveField(
            model_name='volunteering',
            name='SupportText',
        ),
        migrations.AddField(
            model_name='competitionrank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exchangerank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='internshiprank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lecturerank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paperrank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='schoolactivityrank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentcadrerank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='volunteeringrank',
            name='SupportText',
            field=models.TextField(null=True),
        ),
    ]
