# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170501_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranklinks',
            name='role',
        ),
        migrations.AddField(
            model_name='ideologyconstructionrank',
            name='Content',
            field=models.TextField(default=b'', verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AddField(
            model_name='researchprojectrank',
            name='role',
            field=models.CharField(default='\u961f\u5458', max_length=20, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperrank',
            name='rank',
            field=models.CharField(max_length=20, verbose_name=b'\xe8\xae\xba\xe6\x96\x87\xe7\xad\x89\xe7\xba\xa7'),
        ),
    ]
