# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170110_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionrank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='exchangerank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='ideologyconstructionrank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='internshiprank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='lecturerank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='paperrank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='paperrank',
            old_name='Level',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='schoolactivityrank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='studentcadrerank',
            old_name='Complete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='volunteeringrank',
            old_name='Complete',
            new_name='complete',
        ),
    ]
