# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170506_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranklinks',
            name='status',
            field=models.CharField(choices=[(b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8'), (b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87', b'\xe6\x9c\xaa\xe9\x80\x9a\xe8\xbf\x87'), (b'\xe9\x80\x9a\xe8\xbf\x87', b'\xe9\x80\x9a\xe8\xbf\x87')], default=b'\xe5\xbe\x85\xe5\xae\xa1\xe6\xa0\xb8', max_length=10, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
