# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-30 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_major_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completelm',
            options={'verbose_name': '\u4e13\u4e1a\u8bfe\u7a0b\u5bf9\u7167\u8868', 'verbose_name_plural': '\u4e13\u4e1a\u8bfe\u7a0b\u5bf9\u7167\u8868'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
    ]
