# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170111_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competitionrank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competitionrank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exchangerank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exchangerank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ideologyconstructionrank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ideologyconstructionrank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='internshiprank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='internshiprank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturerank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturerank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paperrank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paperrank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='researchprojectrank',
            name='ManagerComplete',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='researchprojectrank',
            name='ManagerScore',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='researchprojectrank',
            name='MemberComplete',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolactivityrank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolactivityrank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentcadrerank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentcadrerank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteeringrank',
            name='complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteeringrank',
            name='score',
            field=models.SmallIntegerField(null=True),
        ),
    ]
