# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170114_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcadre',
            name='StudentNum',
        ),
        migrations.RemoveField(
            model_name='studentcadre',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='studentcadre',
            name='rankNum',
        ),
        migrations.RenameField(
            model_name='studentcadrerank',
            old_name='teacher',
            new_name='student',
        ),
        migrations.DeleteModel(
            name='StudentCadre',
        ),
    ]
