# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-30 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171130_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Complete', verbose_name=b'\xe5\xae\x8c\xe6\x88\x90\xe5\xba\xa6')),
            ],
            options={
                'verbose_name': '\u4e13\u4e1a\u8bfe\u7a0b\u5bf9\u7167\u8868',
                'verbose_name_plural': '\u4e13\u4e1a\u8bfe\u7a0b\u5bf9\u7167\u8868',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('num', models.CharField(max_length=10, verbose_name=b'\xe8\xaf\xbe\xe5\xba\x8f\xe5\x8f\xb7')),
                ('credit', models.PositiveSmallIntegerField(verbose_name=b'\xe5\xad\xa6\xe5\x88\x86')),
                ('time', models.PositiveIntegerField(verbose_name=b'\xe5\xad\xa6\xe6\x97\xb6')),
                ('introduction', models.CharField(max_length=200, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe4\xbb\x8b\xe7\xbb\x8d')),
                ('classTarget', models.CharField(max_length=200, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe7\x9b\xae\xe6\xa0\x87')),
                ('classSort', models.CharField(max_length=50, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe7\xb1\xbb\xe5\x88\xab')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LtoT', to='app.Teacher', verbose_name=b'\xe6\x95\x99\xe5\xb8\x88')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name=b'\xe6\x88\x90\xe7\xbb\xa9')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lesson', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Students', verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xad\xa6\xe5\x8f\xb7')),
            ],
            options={
                'verbose_name': '\u6210\u7ee9',
                'verbose_name_plural': '\u6210\u7ee9',
            },
        ),
        migrations.AddField(
            model_name='completelm',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lesson', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='completelm',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Major', verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
    ]
